# Generated by Django 3.0.8 on 2020-07-31 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200731_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameinvite',
            old_name='game_id',
            new_name='game_url',
        ),
        migrations.RemoveField(
            model_name='gameinvite',
            name='users',
        ),
        migrations.AddField(
            model_name='gameinvite',
            name='from_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invite_from', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameinvite',
            name='to_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invite_to', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
