# Generated by Django 3.0.8 on 2020-09-07 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_gameinvite_game_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameinvite',
            old_name='game_url',
            new_name='game_id',
        ),
    ]
