# Generated by Django 3.0.8 on 2020-09-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20200926_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='time',
            field=models.DecimalField(decimal_places=2, default=60.0, max_digits=6),
        ),
    ]
