# Generated by Django 3.0.8 on 2020-07-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200729_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('stalemate', 'Stalemate'), ('checkmate', 'Checkmate'), ('in_progress', 'In Progress')], default='checkmate', max_length=32),
            preserve_default=False,
        ),
    ]
