# Generated by Django 3.0.8 on 2020-07-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200729_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinvite',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='move',
            name='move_type',
            field=models.CharField(choices=[('castle', 'Castle'), ('en_passant', 'En Passant'), ('regular', 'Regular')], max_length=32),
        ),
    ]
