# Generated by Django 3.0.8 on 2020-07-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200731_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='winner',
            field=models.BooleanField(null=True),
        ),
    ]
