# Generated by Django 3.0.8 on 2020-08-31 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200801_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gameinvite',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameinvite',
            name='declined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='time',
            field=models.IntegerField(default=1800),
        ),
        migrations.AddField(
            model_name='user',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
