# Generated by Django 3.0.8 on 2020-09-07 21:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200901_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinvite',
            name='game_url',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
