# Generated by Django 3.0.8 on 2020-09-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200907_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='status',
            new_name='_status',
        ),
        migrations.AddField(
            model_name='game',
            name='group_channel_name',
            field=models.CharField(default='channel', max_length=512),
            preserve_default=False,
        ),
    ]
