# Generated by Django 3.0.8 on 2020-09-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20200924_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='time',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player',
            name='turn_started_timestamp',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
    ]
