# Generated by Django 3.0.8 on 2020-09-25 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20200924_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='time',
            field=models.DecimalField(decimal_places=2, default=1800.0, max_digits=6),
        ),
    ]
