# Generated by Django 3.0.8 on 2020-09-26 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20200925_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='resigned_colour',
        ),
        migrations.RemoveField(
            model_name='player',
            name='loser',
        ),
        migrations.AddField(
            model_name='player',
            name='draw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='resigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='timeout',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_to_user', to='core.Game'),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to_game', to=settings.AUTH_USER_MODEL),
        ),
    ]
