# Generated by Django 3.0.8 on 2020-07-10 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_client_gameinvite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='channel_layer',
            new_name='channel_name',
        ),
    ]
