# Generated by Django 3.0.8 on 2020-07-28 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200725_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='black_player',
        ),
        migrations.RemoveField(
            model_name='game',
            name='white_player',
        ),
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='gameinvite',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='gameinvite',
            name='to_user',
        ),
        migrations.RemoveField(
            model_name='move',
            name='captured_piece',
        ),
        migrations.RemoveField(
            model_name='move',
            name='special_move',
        ),
        migrations.AddField(
            model_name='gameinvite',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='move',
            name='captured_piece_type',
            field=models.CharField(choices=[('R', 'Rook'), ('Kn', 'Knight'), ('B', 'Bishop'), ('Ki', 'King'), ('Q', 'Queen'), ('P', 'Pawn')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='move',
            name='move_type',
            field=models.CharField(choices=[('CA', 'Castle'), ('EP', 'En Passant'), ('PP', 'Pawn Promotion'), ('REG', 'Regular')], default='REG', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='_user_friends_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.IntegerField(default=1200),
        ),
        migrations.AlterField(
            model_name='gameinvite',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='move',
            name='piece_type',
            field=models.CharField(choices=[('R', 'Rook'), ('Kn', 'Knight'), ('B', 'Bishop'), ('Ki', 'King'), ('Q', 'Queen'), ('P', 'Pawn')], max_length=32),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.BooleanField()),
                ('winner', models.BooleanField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(through='core.Player', to=settings.AUTH_USER_MODEL),
        ),
    ]
