# Generated by Django 3.0.8 on 2020-08-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200731_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='resigned_colour',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('stalemate', 'Stalemate'), ('checkmate', 'Checkmate'), ('in_progress', 'In Progress'), ('resigned', 'Resign')], max_length=32),
        ),
    ]
