# Generated by Django 3.0.8 on 2020-09-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200915_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='loser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='my_turn',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='turn_started_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='_status',
            field=models.CharField(choices=[('stalemate', 'Stalemate'), ('checkmate', 'Checkmate'), ('in_progress', 'In Progress'), ('resigned', 'Resign'), ('timeout', 'Timeout')], default='in_progress', max_length=32),
        ),
        migrations.AlterField(
            model_name='player',
            name='colour',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
