# Generated by Django 3.0.8 on 2020-09-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200915_2115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RenameField(
            model_name='gameinvite',
            old_name='accepted',
            new_name='_accepted',
        ),
        migrations.RenameField(
            model_name='gameinvite',
            old_name='declined',
            new_name='_declined',
        ),
        migrations.RemoveField(
            model_name='player',
            name='my_turn',
        ),
        migrations.AddField(
            model_name='player',
            name='_turn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='_status',
            field=models.CharField(choices=[('stalemate', 'Stalemate'), ('checkmate', 'Checkmate'), ('in_progress', 'In Progress'), ('resign', 'Resign'), ('timeout', 'Timeout')], default='in_progress', max_length=32),
        ),
        migrations.AlterField(
            model_name='player',
            name='time',
            field=models.DecimalField(decimal_places=2, default=1800.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player',
            name='turn_started_timestamp',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
