# Generated by Django 3.0.8 on 2020-09-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_move_notation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='captured_piece_type',
            field=models.CharField(choices=[('R', 'Rook'), ('N', 'Knight'), ('B', 'Bishop'), ('K', 'King'), ('Q', 'Queen'), ('p', 'Pawn')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='piece_type',
            field=models.CharField(choices=[('R', 'Rook'), ('N', 'Knight'), ('B', 'Bishop'), ('K', 'King'), ('Q', 'Queen'), ('p', 'Pawn')], max_length=32),
        ),
        migrations.AlterField(
            model_name='player',
            name='turn_started_timestamp',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
